apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcoin
spec: 
  replicas: 2
  template:
  selector:
    metadata:
      labels:
        app: nodejs
      spec:
      containers:
      name: pcoin
      image: lawrence1910/pcoin:v1
      ports:
      - containerPort: 8080

    