{{- if .Values.serviceLogin.create -}}
apiVersion: v1
kind: ServiceLogin
metadata:
  name: {{ include "Login-service.serviceLoginName" . }}
  labels:
    {{- include "Login-service.labels" . | nindent 4 }}
  {{- with .Values.serviceLogin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
